package dnd

//go:generate go run mage.go services
//go:generate go run mage.go mocks
//go:generate goimports -w ./
//go:generate go fmt ./...
//go:generate gomarkdoc ./models/...
//go:generate gomarkdoc ./example/...
